---
- hosts: deu
  become: true
  vars:
    zabbix_mac_download_url: https://cdn.zabbix.com/zabbix/binaries/stable
    zabbix_agent_version: "6.4"
    zabbix_version_long: "6.4.8"
    zabbix_mac_package: zabbix_agent-{{ zabbix_version_long }}-macos-amd64-openssl.pkg
    zabbix_mac_download_link: "{{ zabbix_mac_download_url }}/{{ zabbix_agent_version }}/{{ zabbix_version_long }}/{{ zabbix_mac_package }}"
  tasks:
# Tasks specific for macOS
  - name: "macOS | Download the Zabbix package"
    ansible.builtin.get_url:
      url: "{{ zabbix_mac_download_link }}"
      dest: "/tmp/{{ zabbix_mac_package }}"
      mode: 0644

  - name: "macOS | Install the Zabbix package"
    ansible.builtin.command: installer -pkg "/tmp/{{ zabbix_mac_package }}" -target /
    become: true

  - name: "Copy config"
    ansible.builtin.copy:
      src: zabbix_agentd.conf
      dest: /usr/local/etc/zabbix/zabbix_agentd.conf
      owner: root
      group: wheel
      mode: '0644'

  - name: Restart zabbix
    community.general.launchd:
      name: com.zabbix.zabbix_agentd
      state: restarted